
const products = [{
		id: 1,
		name: "Narty Salomon",
		rating: 3.7,
		description: "Super narty na zimę i na lato.",
		price: 500,
		image: require("./assets/images/product-1.jpg"),
	},
	{
		id: 2,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-2.jpg"),
	},
	{
		id: 3,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-3.jpg"),
	},
	{
		id: 4,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-4.jpg"),
	},
	{
		id: 5,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-5.jpg"),
	},
	{
		id: 6,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-6.jpg"),
	},
	{
		id: 7,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-7.jpg"),
	},
	{
		id: 8,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-8.jpg"),
	},
	{
		id: 9,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-9.jpg"),
	},
	{
		id: 10,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-10.jpg"),
	},
	{
		id: 11,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-11.jpg"),
	},
	{
		id: 12,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-12.jpg"),
	},
	{
		id: 13,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-13.jpg"),
	},
	{
		id: 14,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-14.jpg"),
	},
	{
		id: 15,
		name: "Kask Rossignol Jednorożec",
		rating: 5.0,
		description: "Znakomity kask dla dziewczynek w wieku do 10 lat i studentów informatyki w wieku 20-26 lat",
		price: 420.20,
		image: require("./assets/images/product-15.jpg"),
	},


]

export default products